### ISSUE TITLE
Question regarding 2Dmodel implementation

### ISSUE THREAD

**Issue by cpknowles** [pf4d/cslvr#10]
Hello, I was hoping you might be able to answer a question for me.

I am currently trying to incorporate your balancevelocity method for a 2Dmodel, and in starting the vertical integration calculations I receive this error:

```
in deform_mesh_to_geometry
    max_height  = self.mesh.coordinates()[:,2].max()
IndexError: index 2 is out of bounds for axis 1 with size 2
```
This error occurs for every function that tries to calculate with x[2] or dx(2).

I am currently using a basic 2dmesh created in GMSH, and is purely in the xy plane so I have no x[2] terms. I figured that deform_mesh_to_geometry(Surface,Bed) was appending a x[2] term to each (x[0],x[1]) location based on my surface and bed values? Do I need to have a mesh that is 3D already? 

Any insight you have would be greatly appreciated! The end result of this program is to model basic glacial flow with tributaries.

Thanks for your time,
Christopher

**Comment by pf4d** [comment]
Hi Christopher,

The ''deform_mesh_to_geometry'' method adjusts the z-coordinates of 3D meshes to a desired geometry.  The 2D meshes, while they may also have a third dimension, does not require deformation.  This is because the physics for all map-plane problems with the current version of CSLVR ignore this dimension.  Therefore, you do not need to call this method.

-E

**Comment by pf4d** [comment]
For some extra help (besides the half-finished tutorial hosted on ReadTheDocs), see the thesis:

https://arxiv.org/abs/1609.02190

**Comment by cpknowles** [comment]
Alright cool! Then if I understand then I don't really have to deal with the vertical integration methods in D2Model at all. Well I can't even try because they require a dx(2) term to solve for our 'a' term. 

So instead I should just directly deal with BalanceVelocity, because from what I can tell in the thesis, it captures what the vertical integration would be doing by solving for the d_x and d_y! Unless that is the wrong conclusion, I should be good to go then, just need to define the right slope for my surface and time step now. 

Thanks for your help!!
Christopher

**Comment by pf4d** [comment]
Christopher,

I see how the `vert_integrate` method would confuse.  It is meant only for lateral sub-meshes taken from 3D meshes, or "transects."

You can use any imposed direction of flow, as indicated in the thesis, be that data or mathematical functions.  Line 31 and 32 of the balance velocity [script](https://github.com/pf4d/cslvr/blob/master/simulations/greenland/balance_velocity/balance_velocity.py) for Greenland demonstrate two ways of using data.

Thanks for the interest,
Evan
