### ISSUE TITLE
Dolfin RuntimeError in solving balance velocity problem, Antarctica

### ISSUE THREAD

**Issue by felbelles** [pf4d/cslvr#8]
Hi all, 

I'm trying to calculate balance velocities for Antarctica using the (slightly modified) generic balance_velocity.py script (attached).

I run into a RuntimeError in the solve part of calculating the balance velocities (see below).

I've attached the full output log from the balance velocity calculation. The Antarctic data and meshes I used were downloaded using the scripts provided in the cslvr package.

Any help would be greatly appreciated!

Thanks, 
Felicity

Traceback (most recent call last):
  File "simulations/antarctica/balance_velocity/balance_velocity.py", line 35, in <module>
    bv.solve(annotate=False)
  File "/home/felicity/software/cslvr/cslvr/balancevelocity.py", line 98, in solve
    solve(self.a_dSdx == self.L_dSdx, model.Nx, annotate=annotate)
  File "/home/felicity/software/dolfin-adjoint/dolfin_adjoint/solving.py", line 357, in solve
    ret = backend.solve(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dolfin/fem/solving.py", line 297, in solve
    _solve_varproblem(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dolfin/fem/solving.py", line 321, in _solve_varproblem
    form_compiler_parameters=form_compiler_parameters)
  File "/usr/lib/python2.7/dist-packages/dolfin/fem/solving.py", line 82, in __init__
    cpp.LinearVariationalProblem.**init**(self, a, L, u, bcs)
  File "/usr/lib/python2.7/dist-packages/dolfin/cpp/fem.py", line 2412, in **init**
    _fem.LinearVariationalProblem_swiginit(self,_fem.new_LinearVariationalProblem(a, L, u, bcs))
RuntimeError: 

**\* -------------------------------------------------------------------------
**\* DOLFIN encountered an error. If you are not able to resolve this issue
**\* using the information listed below, you can ask for help at

---

**\*     fenics@fenicsproject.org

---

**\* Remember to include the error message listed below and, if possible,
**\* include a _minimal_ running example to reproduce the error.

---

**\* -------------------------------------------------------------------------
**\* Error:   Unable to define linear variational problem a(u, v) = L(v) for all v.
**\* Reason:  Expecting the solution variable u to be a member of the trial space.
**\* Where:   This error was encountered inside LinearVariationalProblem.cpp.
**\* Process: 0

---

**\* DOLFIN version: 1.6.0
**\* Git changeset:  unknown
**\* -----------------------------------------------------------------------

[balance_velocity.log.txt](https://github.com/pf4d/cslvr/files/144022/balance_velocity.log.txt)
[balance_velocity.py.txt](https://github.com/pf4d/cslvr/files/144021/balance_velocity.py.txt)

**Comment by pf4d** [comment]
Hi felbelles!

I've updated the instantiation process for all the model instances to automatically set the mesh and generate function spaces, and have not made sure all of the test scripts were updated.

So, the reason you got that error is because two different function spaces were being created.

I've updated the example to reflect new syntax:

https://github.com/pf4d/cslvr/blob/dev/simulations/antarctica/balance_velocity/balance_velocity.py

Thanks!
