### ISSUE TITLE
Issues with import cslvr

### ISSUE THREAD

**Issue by cpknowles** [pf4d/cslvr#9]
I am attempting to use the command given in the installation 
`from cslvr import *`
when I do so I receive an error

>  AttributeError: type object 'LocalSolver' has no attribute 'LU'

This error was given after a traceback, the last print out (of 10) reading

/usr/local/lib/python2.7/dist-packages/dolfin_adjoint/localsolver.py in LocalSolver()
     48 class LocalSolver(dolfin.LocalSolver):
---> 49     def **init**(self, a, L = None, solver_type = dolfin.LocalSolver.LU, **kwargs):
     50         dolfin.LocalSolver.**init**(self, a, L, solver_type)
     51         factorize = kwargs.pop("factorize", False)

This occurs both in ipython and when I try and run the `download_*.py`. Any ideas as to how I can fix this? I am currently using Ubuntu 12.04, which isn't the prescribed version for this installation. Could that be the issue?

**Comment by pf4d** [comment]
Can you import fenics and dolfin_adjoint?

**Comment by cpknowles** [comment]
I can import fenics, but dolfin_adjoint gives the same error that the import cslvr gives. 

I installed dolfin_adjoint through 
`git clone -b dolfin-adjoint-1.6 https://bitbucket.org/dolfin-adjoint/dolfin-adjoint`

but utilized the fork https://github.com/pf4d/dolfin-adjoint.git from your page, so the command became
`git clone -b dolfin-adjoint-1.6 https://github.com/pf4d/dolfin-adjoint.git`

**Comment by pf4d** [comment]
Did you follow the instructions for dolfin-adjoint installation [here](http://dolfin-adjoint-doc.readthedocs.io/en/latest/download/index.html)?

**Comment by cpknowles** [comment]
So I tried doing the binary package install because that is what we did for fenics, but when I do these commands
`sudo apt-add-repository ppa:libadjoint/ppa`
`sudo apt-get update`
 `sudo apt-get install python-dolfin-adjoint`
I receive a prompt that states 

> E: Unable to locate package python-dolfin-adjoint

**Comment by pf4d** [comment]
Sorry, you should install as suggested in the "From source" section.  You git clone my fork of the dolfin-adjoint repository, as you've already done, then use the commands:

```
export PYTHONPATH=<path to dolfin-adjoint>:$PYTHONPATH
```

libadjoint needs to be compiled with:

```
cd libadjoint
mkdir build; cd build
cmake -DCMAKE_INSTALL_PREFIX=<install directory> ..
make install
```

**Comment by cpknowles** [comment]
So that all worked! I was able to import dolfin_adjoint in ipython and it was happy, but import cslvr still is not, because gmshpy is now having issues.

I can run gmsh fine and it reads that it has a 2.12.1-dynamic-svn at the bottom, and I copied all of the directories over to /usr/local as well.
But when I cd into gmshpy and try and install, I run into a fatal error that a certain .h file doesn't exist. When I go to the include directory it indeed does not have meshPartitionObjects.h. Any thoughts? 

cpknowles@kic:~/Desktop/gmsh-2.12.1-dynamic-svn-Linux/gmshpy$ sudo python setup.py install;
running install
running build
running build_py
running build_ext
building 'gmshpy._gmshGeo' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DSWIG=1 -I./extra_include/ -I../include/gmsh/ -I/usr/include/python2.7 -c src/gmshGeoPYTHON_wrap.cxx -o build/temp.linux-x86_64-2.7/src/gmshGeoPYTHON_wrap.o
cc1plus: _warning_: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from **src/gmshGeoPYTHON_wrap.cxx:3722:0:
../include/gmsh/discreteFace.h:13:34: fatal error:** meshPartitionObjects.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Thanks for your time on all of this by the way, I realize these must be basic questions...

**Comment by pf4d** [comment]
Oh --  yeah for some reason gmsh 2.12 does not work, I have to use gmsh dynamic 2.10.1 to get it to work...

**Comment by cpknowles** [comment]
Ahh, that would be the issue then. I can't seem to locate a version of gmsh dynamic 2.10.1. The binaries that are kept on the gmsh website only carry the latest version of dynamic it seems, and the non-dynamic versions don't contain a gmshpy folder! Do you know where I could locate a version of dynamic 2.10.1?

**Comment by pf4d** [comment]
Ah yes, let me see here...  [AH HA!](https://www.dropbox.com/s/hp64kx6wh790sf6/gmsh.tgz?dl=1)

Like I always say, better to have a GMSH and not need it than to need a GMSH and not have it...

**Comment by cpknowles** [comment]
IT WORKS!! I can now import cslvr.

Thanks so much for the help! I should (hopefully) be fine from here on out.

**Comment by pf4d** [comment]
cheers!
